version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  file:
    class: logging.FileHandler
    formatter: standard
    filename: 'app.log'
loggers:
  uvicorn:
    handlers: [file]
    level: INFO
  uvicorn.error:
    handlers: [file]
    level: INFO
  uvicorn.access:
    handlers: [file]
    level: INFO